# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 01. Scala Build & Test

on:
  push:
    branches: ["**"]   # Match all branches 
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        cache: 'sbt'
        
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
      
    - name: Run tests
      run: SBT_OPTS="-Xmx8G  -Duser.timezone=GMT" TEST_THREAD_CNT="2" sbt test

      
