# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala Build & Test Native

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
   
    strategy:
         #let the other platforms build even if one fails for now anyway
        fail-fast: false
        matrix:
          os:
              - ubuntu-latest
              - ubuntu-24.04-arm
              - macos-latest
              - windows-latest
          include:
              # defaults command is the *nix command line but if windows use the windows specific
              - command: SBT_OPTS="-Xmx8G  -Duser.timezone=GMT" TEST_THREAD_CNT="2" sbt -v nativeImage test 
              - command: set SBT_OPTS="-Xmx8G  -Duser.timezone=GMT" & set TEST_THREAD_CNT="2" & sbt -v nativeImage test 
                os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        cache: 'sbt'
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: ${{ matrix.command }}
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    #- name: Upload dependency graph
    # uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
